apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  mqtt.config: |
    listener {{ template "configuredPort" . }} {{ template "configuredAddress" . }}
    protocol mqtt
    {{ if .Values.configuration.persistence.enabled }}
    persistence true
    persistence_location /mosquitto/data
    {{ end }}
    allow_anonymous true
