apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      volumes:
        - name: mqtt-config
          configMap:
            name: mqtt
            items:
            - key: mqtt.config
              path: mosquitto.conf
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.15
          volumeMounts:
            - name: mqtt-config
              mountPath: /mosquitto/config          
