apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}
            items:
            - key: mqtt.config
              path: mosquitto.conf
        {{ if .Values.configuration.persistence.enabled }}              
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: mqtt-data
        {{ end }}
      containers:
        - name: {{ .Release.Name }}
          image: eclipse-mosquitto:{{ .Chart.AppVersion }}
          volumeMounts:
            - name: mqtt-config
              mountPath: /mosquitto/config
            {{ if .Values.configuration.persistence.enabled }}              
            - name: mqtt-data
              mountPath: /mosquitto/data
            {{ end }}
      securityContext:
        runAsUser: 1883
        runAsGroup: 1883
        fsGroup: 1883
