apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP

metadata:
  name: mqtt

spec:
  entryPoints:
    - mqtt

  routes:
    - match: HostSNI(`*`)
      services:
        - name: mqtt
          port: 1883