apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP

metadata:
  name: {{ .Release.Name }}

spec:
  entryPoints:
    - mqtt

  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ .Release.Name }}
          port: 1883