{{- if .Values.configuration.persistence.enabled -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.configuration.persistence.storageClassName | default "local-path" }}
  resources:
    requests:
      storage: {{ .Values.configuration.persistence.size | default "256Mi" }}

{{- end -}}